// <auto-generated />
using System;
using BestDeal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BestDeal.Migrations
{
    [DbContext(typeof(BestDealContext))]
    [Migration("20190616210633_fixRazmak")]
    partial class fixRazmak
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BestDeal.Models.Artikal", b =>
                {
                    b.Property<int>("IdArtikla");

                    b.Property<double>("CijenaArtikla");

                    b.Property<string>("DetaljniOpis")
                        .IsRequired();

                    b.Property<string>("KratkiOpis")
                        .IsRequired();

                    b.Property<string>("NazivArtikla")
                        .IsRequired();

                    b.Property<int>("TipArtiklaidTipa");

                    b.Property<string>("URLMaleSlike1")
                        .IsRequired();

                    b.Property<string>("URLSlike1")
                        .IsRequired();

                    b.Property<string>("tipNaziv");

                    b.HasKey("IdArtikla");

                    b.HasIndex("TipArtiklaidTipa");

                    b.ToTable("Artikal");

                    b.HasData(
                        new
                        {
                            IdArtikla = 1,
                            CijenaArtikla = 700.0,
                            DetaljniOpis = "Povežite se sa cijenjenim HP 250 notebook računarima. Završajite poslovne zadatke sa Intel® tehnologijom, osnovnim alatima za saradnju koji su učitani na HP 250. Izdržljiva šasija pomaže zaštiti laptopa od strogosti dana.",
                            KratkiOpis = "Vrhunski laptop za prosječnog korisnika!",
                            NazivArtikla = "HP 250 G6",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://static.toiimg.com/photo/60104728/HP-15-BS542TU-2EY84PA-Laptop-Core-i3-6th-Gen4-GB1-TBDOS.jpg",
                            URLSlike1 = "https://images-na.ssl-images-amazon.com/images/I/81iq991JMEL._SL1500_.jpg",
                            tipNaziv = "Laptopi"
                        },
                        new
                        {
                            IdArtikla = 2,
                            CijenaArtikla = 850.0,
                            DetaljniOpis = "With up to Intel Pentium® Silver processing, the IdeaPad D330 has real computing power—and all the fun and mobility of a lightweight tablet. From multitasking to connecting with friends online and streaming shows, the D330 gives you the freedom to do more, anywhere.",
                            KratkiOpis = "Odličan izbor za putovanja!",
                            NazivArtikla = "LENOVO IdeaPad D330",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://images-na.ssl-images-amazon.com/images/I/41FYl0JeBtL._SX425_.jpg",
                            URLSlike1 = "https://www.wootware.co.za/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/f/x/fxpapmt2ez1.jpg"
                        },
                        new
                        {
                            IdArtikla = 3,
                            CijenaArtikla = 2250.0,
                            DetaljniOpis = @"1.6GHz dual‑core 8th‑generation Intel Core i5 processor Turbo Boost up to 3.6GHz
 Retina display 13.3-inch (diagonal) LED-backlit display with IPS technology; 2560 - by - 1600 native resolution at 227 pixels per inch with support for millions of colors
 8GB 2133MHz LPDDR3 memory
 128GB SSD storage
 Intel UHD Graphics 617 Touch ID
 Force Touch trackpad
 Two Thunderbolt 3 ports
 Backlit Keyboard - US English",
                            KratkiOpis = "Vrhunski laptop za one koji žele više!",
                            NazivArtikla = "MacBook Air",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5998/5998800_sd.jpg",
                            URLSlike1 = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5998/5998800_sd.jpg"
                        },
                        new
                        {
                            IdArtikla = 4,
                            CijenaArtikla = 1500.0,
                            DetaljniOpis = @"Procesor: Intel Core i5-7200 na 2.5GHz 
 RAM: 8GB DDR3 
 SSD: 256GB 
 Grafika: Intel HD Graphics 620 
 Display: 14""FHD IPS LED",
                            KratkiOpis = "Laptop koji će ispuniti svakodnevne zahtjeve njihovih korisnika!",
                            NazivArtikla = "Acer Swift 5",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://www.notebookcheck.net/fileadmin/Notebooks/Acer/Swift_5_SF515-51T-70UX/4zu3_Acer_Swift_5_SF515_51T.jpg",
                            URLSlike1 = "https://www.notebookcheck.net/fileadmin/Notebooks/Acer/Swift_5_SF515-51T-70UX/4zu3_Acer_Swift_5_SF515_51T.jpg"
                        },
                        new
                        {
                            IdArtikla = 5,
                            CijenaArtikla = 1800.0,
                            DetaljniOpis = @"CPU Intel Core i7 8550U (1.80 GHz up to 4.00 GHz) 8MB 
 Radna memorija DDR4 8GB
 HDD SSD 256GB 
 VGA Nvidia GTX1050 4GB DDR5 128 bita 
 Ekran 15.6 LED full HD (1920x1080) 
 Webcam, wifi, BT, HDMI, USB 3.0 x 2 
 USB-C, LAN, cardreader, osvjetljena tastatura 
 Windows 10 Pro licenca 64 bita",
                            KratkiOpis = "Entry level gaming laptop!",
                            NazivArtikla = "ASUS FX570UD",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://images-na.ssl-images-amazon.com/images/I/81Lr70XWFWL._SX425_.jpg",
                            URLSlike1 = "https://images-na.ssl-images-amazon.com/images/I/81Lr70XWFWL._SX425_.jpg"
                        },
                        new
                        {
                            IdArtikla = 6,
                            CijenaArtikla = 700.0,
                            DetaljniOpis = @"15,6 inch HD (1366×768) AG 
 Pentium N5000 ( 4M, up to 2.7GHz) 
 4GB DD4 
 1TB HDD (5400 rpm) 
 DVD RW 
 Intel UHD Graphics 
  4-Cell Batt (40Whr) 
 Ubunt Linux 16.04, Ultra Blue",
                            KratkiOpis = "Laptop namijenjen za svakodnevne potrebe!",
                            NazivArtikla = "Dell Inspiron 15-3582",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://www.procomp.ba/17980-large_default/dell-inspiron-15-3582.jpg",
                            URLSlike1 = "https://www.procomp.ba/17980-large_default/dell-inspiron-15-3582.jpg"
                        },
                        new
                        {
                            IdArtikla = 7,
                            CijenaArtikla = 1400.0,
                            DetaljniOpis = "Core i5-8265U, 4GB, 1TB, 14.0\" FHD, Intel UHD 620, FgrPr, Cam & Mic, No optical drive, WLAN + BT, Backlit Kb, 3 Cell, Ubuntu",
                            KratkiOpis = "Laptop za Linux entuzijaste!",
                            NazivArtikla = "Dell Vostro 5481",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "http://i.dell.com/sites/csimages/Video_Imagery/all/vostro-1471.jpg",
                            URLSlike1 = "http://i.dell.com/sites/csimages/Video_Imagery/all/vostro-1471.jpg"
                        },
                        new
                        {
                            IdArtikla = 8,
                            CijenaArtikla = 3000.0,
                            DetaljniOpis = @"Procesor: Intel Core i7 8750H 2.2 GHz (6 Cores) 
 Memorija (RAM): 16 GB DDR4 
 Hard disk: 512 GB, SSD 
 Grafička: Nvidia GeForce GTX 1050 
 Mreža: Wireless, LAN 
 Ostalo: Card Reader, HDMI, USB3.1 , VGA ,Fingerprint",
                            KratkiOpis = "Laptop koji će učiniti svaki zadatak da se sa lahkoćom riješi!",
                            NazivArtikla = "ASUS UX580GD-BO009R",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://www.comtradeshop.com/img/products/2018-08-31/asus-zenbook-pro-ux580gd-bo009r-laptop-15-6-quot-full-hd-ips-intel-hexa-core-i7-8750h-16gb-512gb-ssd-nvme-geforce-gtx1050-4gb-gddr5-win10-pro_IGYtV_3.jpg",
                            URLSlike1 = "https://www.comtradeshop.com/img/products/2018-08-31/asus-zenbook-pro-ux580gd-bo009r-laptop-15-6-quot-full-hd-ips-intel-hexa-core-i7-8750h-16gb-512gb-ssd-nvme-geforce-gtx1050-4gb-gddr5-win10-pro_IGYtV_3.jpg"
                        },
                        new
                        {
                            IdArtikla = 9,
                            CijenaArtikla = 8000.0,
                            DetaljniOpis = @"Model procesora: i9-8950HK 2.90GHZ, 8 jezgri 
 RAM: 32 GB 
 SSD kapacitet (GB): 1500GB SSD 
 Proizvođač graf. kartice: NVIDIA RTX 2080 
 Rezolucija: 1920x1080 144Hz refresh rate",
                            KratkiOpis = "Laptop koji je u stanju podržati sve TripleA naslove igrica na maksimalnoj grafici!",
                            NazivArtikla = "ASUS ROG G703GX",
                            TipArtiklaidTipa = 1,
                            URLMaleSlike1 = "https://c1.neweggimages.com/NeweggImage/ProductImage/34-235-121-V30.jpg",
                            URLSlike1 = "https://c1.neweggimages.com/NeweggImage/ProductImage/34-235-121-V30.jpg"
                        },
                        new
                        {
                            IdArtikla = 10,
                            CijenaArtikla = 1350.0,
                            DetaljniOpis = @"Rezolucija: 6.4 inches 1440x3040 pixels, 19:9 ratio (~522 ppi density) 
 OS: Android 9.0 (Pie) 
 Procesor: Exynos 9820 (8nm) 
 GPU: Mali-G76 MP12 
 Card slot: microSD, up to 1 TB (uses shared SIM slot) - dual SIM model only 
 Internal: 1 TB, 12 GB RAM, 128/512 GB, 8 GB RAM 
 Glavna kamera: Triple sensor(12MP, 12MP, 16MP) 
 Prednja kamera: Dual (10MP, 8MP) 
 Baterija: 4100mAh",
                            KratkiOpis = "Sljedeća generacija galaxy uređaja!",
                            NazivArtikla = "Samsung Galaxy S10 Plus 128GB",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s10-plus-new.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s10-plus-new.jpg"
                        },
                        new
                        {
                            IdArtikla = 11,
                            CijenaArtikla = 1350.0,
                            DetaljniOpis = @"Rezolucija: 5.8 inches 1125 x 2436 pixels, 19.5:9 ratio (~458 ppi density) 
 OS: iOS 11.1.1, upgradable to iOS 12.3 
 Procesor: Apple A11 Bionic (10 nm) 
 GPU: Apple GPU (three-core graphics) 
 Card slot: No 
 Internal: 64/256 GB, 3 GB RAM 
 Glavna kamera: Dual sensor(12MP, 12MP) 
 Prednja kamera: Dual (7MP, TOF 3D kamera) 
 Baterija: 2716mAh",
                            KratkiOpis = "Savršenstvo u svakom pogledu!",
                            NazivArtikla = "Iphone X Silver 64GB",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-x.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/apple-iphone-x.jpg"
                        },
                        new
                        {
                            IdArtikla = 12,
                            CijenaArtikla = 1290.0,
                            DetaljniOpis = @"Rezolucija: 6.47 inches 1080 x 2340 pixels, 19.5:9 ratio (~398 ppi density) 
 OS: Android 9.0 (Pie); EMUI 9.1 
 Procesor: HiSilicon Kirin 980 (7 nm) 
 GPU: Mali-G76 MP12 
 Card slot: NM (Nano Memory), up to 256GB (uses shared SIM slot) 
 Internal: 128/256/512 GB, 8 GB RAM or 128 GB, 6 GB RAM 
 Glavna kamera: Quad sensors(40MP, Periscope 8MP, 20MP, TOF 3D kamera) 
 Prednja kamera: Single (32MP) 
 Baterija: 4200mAh",
                            KratkiOpis = "Spoznaj moć kamere uz Huawei P30 PRO",
                            NazivArtikla = "Huawei P30 PRO 128GB",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/huawei-p30-pro.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/huawei-p30-pro.jpg"
                        },
                        new
                        {
                            IdArtikla = 13,
                            CijenaArtikla = 1450.0,
                            DetaljniOpis = @"Rezolucija: 6.67 inches 1440 x 3120 pixels, 19.5:9 ratio (~516 ppi density) 
 OS: Android 9.0 (Pie); OxygenOS 9.5.7 
 Procesor: Qualcomm SDM855 Snapdragon 855 (7 nm) 
 GPU: Adreno 640 
 Card slot: No 
 Internal: 256 GB, 8/12 GB RAM or 128 GB, 6 GB RAM 
 Glavna kamera: Triple sensors(48MP, 8MP, 16MP) 
 Prednja kamera: Motorized pop-up 16 MP 
 Baterija: 4000mAh",
                            KratkiOpis = "Brzina koja nije ravna nijednom drugom!",
                            NazivArtikla = "OnePlus 7 Pro",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/huawei-p30-pro.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/huawei-p30-pro.jpg"
                        },
                        new
                        {
                            IdArtikla = 14,
                            CijenaArtikla = 1100.0,
                            DetaljniOpis = @"Rezolucija: 5.99 inches 1440 x 2880 pixels, 18:9 ratio (~538 ppi density) 
 OS: Android 9.0 (Pie); Android One 
 Procesor: Qualcomm SDM845 Snapdragon 845 (10 nm) 
 GPU: Adreno 630 
 Card slot: No 
 Internal: 128 GB, 6 GB RAM 
 Glavna kamera: Five sensors(5x 12MP f/1.8) 
 Prednja kamera: 20 MP 
 Baterija: 3320mAh",
                            KratkiOpis = "Upoznaj tehnologiju koja ispunjava vaše poslovne potrebe!",
                            NazivArtikla = "Nokia 9 PureView",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = @"https://cdn2.gsmarena.com/vv/bigpic
okia-9-pureview-.jpg",
                            URLSlike1 = @"https://cdn2.gsmarena.com/vv/bigpic
okia-9-pureview-.jpg"
                        },
                        new
                        {
                            IdArtikla = 15,
                            CijenaArtikla = 550.0,
                            DetaljniOpis = @"Rezolucija: 6.0 inches 1080 x 2520 pixels, 21:9 ratio (~457 ppi density) 
 OS: Android 9.0 (Pie) 
 Procesor: Qualcomm SDM630 Snapdragon 630 (14 nm) 
 GPU: Adreno 508 
 Card slot: microSD, up to 1 TB (uses shared SIM slot) 
 Internal: 64 GB, 3 GB RAM or 4 GB (for China only) 
 Glavna kamera: Dual (13MP, 5MP) 
 Prednja kamera: 8 MP 
 Baterija: 2870mAh",
                            KratkiOpis = "Upoznaj tehnologiju koja ispunjava vaše poslovne potrebe!",
                            NazivArtikla = "Sony Xperia 10",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/sony-xperia-10-.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/sony-xperia-10-.jpg"
                        },
                        new
                        {
                            IdArtikla = 16,
                            CijenaArtikla = 550.0,
                            DetaljniOpis = @"Rezolucija: 6.0 inches 1080 x 2520 pixels, 21:9 ratio (~457 ppi density) 
 OS: Android 9.0 (Pie) 
 Procesor: Qualcomm SDM630 Snapdragon 630 (14 nm) 
 GPU: Adreno 508 
 Card slot: microSD, up to 1 TB (uses shared SIM slot) 
 Internal: 64 GB, 3 GB RAM or 4 GB (for China only) 
 Glavna kamera: Dual (13MP, 5MP) 
 Prednja kamera: 8 MP 
 Baterija: 2870mAh",
                            KratkiOpis = "Upoznaj tehnologiju koja ispunjava vaše poslovne potrebe!",
                            NazivArtikla = "Sony Xperia 10",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/sony-xperia-10-.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/sony-xperia-10-.jpg"
                        },
                        new
                        {
                            IdArtikla = 17,
                            CijenaArtikla = 1800.0,
                            DetaljniOpis = @"Rezolucija: 6.4 inches 1440 x 3120 pixels, 19.5:9 ratio (~538 ppi density) 
 OS: Android 9.0 (Pie) 
 Procesor: Qualcomm SDM855 Snapdragon 855 (7 nm) 
 GPU: Adreno 640 
 Card slot: microSD, up to 1 TB (dedicated slot)
 Internal: 128 GB, 6 GB RAM 
 Glavna kamera: Triple (12MP, 12MP, 16MP) 
 Prednja kamera:Dual 8 MP, 5 MP 
 Baterija: 4000mAh",
                            KratkiOpis = "Budite prvi koji će doživjeti novu eru 5G mreže!",
                            NazivArtikla = "LG V50 ThinkQ 5G",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/lg-gv50-thinq-.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/lg-gv50-thinq-.jpg"
                        },
                        new
                        {
                            IdArtikla = 18,
                            CijenaArtikla = 600.0,
                            DetaljniOpis = @"Rezolucija: 5.5 inches 1440 x 2560 pixels, 16:9 ratio (~534 ppi density) 
 OS: Android 7.1 (Nougat), upgradable to Android 9.0 (Pie); Sense UI 
 Procesor: Qualcomm MSM8998 Snapdragon 835 (10 nm) 
 GPU: Adreno 540 
 Card slot: microSD, up to 1 TB (uses shared SIM slot) - dual SIM model only
 Internal: 128 GB, 6 GB RAM or 64 GB, 4 GB RAM 
 Glavna kamera: Main (12MP f/1.7) 
 Prednja kamera: 16MP f/2.0 
 Baterija: 3000mAh",
                            KratkiOpis = "Ako želite da idete za kvalitetom i vrijednosti, vaš izbor je HTC!",
                            NazivArtikla = "HTC U11",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/htc-u11.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/htc-u11.jpg"
                        },
                        new
                        {
                            IdArtikla = 19,
                            CijenaArtikla = 800.0,
                            DetaljniOpis = @"Rezolucija: 6.39 inches 1080 x 2340 pixels, 19.5:9 ratio (~403 ppi density) 
 OS: Android 9.0 (Pie); ZUI 11 
 Procesor: Qualcomm SDM855 Snapdragon 855 (7 nm) 
 GPU: Adreno 640 
 Card slot: microSD, up to 1 TB (uses shared SIM slot) 
 Internal: 512 GB, 12 GB RAM or 256 GB, 8 GB RAM or 128 GB, 6/8 GB RAM 
 Glavna kamera: Quad (48MP, 8MP, 16MP, 2MP) 
 Prednja kamera: 32MP f/2.0 
 Baterija: 4000mAh",
                            KratkiOpis = "Vrhunska tehnologija po pristupačnoj cijeni!",
                            NazivArtikla = "Lenovo Z6 Pro",
                            TipArtiklaidTipa = 2,
                            URLMaleSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/lenovo-z6-pro.jpg",
                            URLSlike1 = "https://cdn2.gsmarena.com/vv/bigpic/lenovo-z6-pro.jpg"
                        },
                        new
                        {
                            IdArtikla = 20,
                            CijenaArtikla = 1600.0,
                            DetaljniOpis = @"System: Intel Core i5-9400f 2.9GHz 6-Core | Intel B360 Chipset | 8GB DDR4 | 120GB SSD | 1TB HDD | Genuine Windows 10 Home 64-bit 
 Graphics: NVIDIA GeForce GTX 1660 6GB Video Card | 1x HDMI | 1x DisplayPort 
 Connectivity: 6 x USB 3.1 | 2 x USB 2.0 | 1x RJ-45 Network Ethernet 10/100/1000 | 802.11AC Wi-Fi | Audio: 7.1 Channel | Gaming ",
                            KratkiOpis = "Gaming računar koji će zasititi i one koje koji traže više!",
                            NazivArtikla = "CyberPowerPC Xtreme",
                            TipArtiklaidTipa = 3,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/71DvG2FjM+L._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/71DvG2FjM+L._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 21,
                            CijenaArtikla = 1200.0,
                            DetaljniOpis = @"8th Generation Intel Core i5-8250U Processor 1.6GHz (Up to 3.4GHz); Operating System Architecture: 64-bit 
 23.8 inches Full HD (1920 x 1080) Widescreen Edge-to-Edge LED Back-lit Display 
 12GB DDR4 2400MHz Memory & 1TB 5400RPM SATA Hard Drive 802.11ac Wi-Fi, Gigabit Ethernet LAN & Bluetooth 4.2LE",
                            KratkiOpis = "All In One Desktop računar za minimalne prostore!",
                            NazivArtikla = "Acer Aspire AIO Desktop",
                            TipArtiklaidTipa = 3,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/71YktzGiStL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/71YktzGiStL._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 22,
                            CijenaArtikla = 400.0,
                            DetaljniOpis = @"HP 8300 Intel I5 Quad-Core 3.2 GHz Processor 
 8GB RAM, 500GB Hard Drive, DVD Optical Drive 
 Operativni sitem: Windows 10 Professional",
                            KratkiOpis = "Računar za svakodnevne potrebe!",
                            NazivArtikla = "HP 8300 Elite",
                            TipArtiklaidTipa = 3,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/41ZLGAJEh7L._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/41ZLGAJEh7L._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 23,
                            CijenaArtikla = 800.0,
                            DetaljniOpis = @"8th Generation Intel Core i3-8100 Processor (3.6GHz) 
 8GB DDR4 2666MHz RAM Memory & 16GB Intel Optane Memory 
 1TB 7200RPM SATA Hard Drive & 8X DVD-Writer Double-Layer Drive (DVD-RW) 
 802.11ac WiFi, Gigabit Ethernet LAN & Bluetooth 5.0. Maximum Power Supply Wattage - 300 W 
 1 - USB 3.1 Type C Gen 2 port (up to 10 Gbps), 1 - USB 3.1 Gen 2 Port, 1 - USB 3.1 Gen 1 Port, 4 - USB 2.0 Ports & 2 - HDMI Ports & 1 - VGA Port",
                            KratkiOpis = "Ovaj računar je solidan performer čija cijena će iznenaditi prave poznavaoce hardvera!",
                            NazivArtikla = "Acer Aspire TC-885-ACCFLi30",
                            TipArtiklaidTipa = 3,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/61Ybzz3P25L._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/61Ybzz3P25L._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 24,
                            CijenaArtikla = 1300.0,
                            DetaljniOpis = @"Izgrađen je za igre koje traže ozbiljne performanse.Pažljivo dizajniran za nadogradnju.Brza tehnologija koja je spremna za budućnost 
 Maksimalno povećajte kapacitet igranja. Velika snaga obrade sa 2. generacijom AMD Ryzen 7 procesora 
 Sa 16 GB DDR4 RAM-a, ovaj gaming desktop je ugrađen sa brzim memorijama kako bi se osigurala super-pogonska izvedba i intenzivni multitasking 
 Amd Radeon RX580 Grafika sa 4GB GDDR5 memorije za brži, glatkiji gameplay",
                            KratkiOpis = "Doživite sljedeću generaciju igara sa ovom gaming računarom!",
                            NazivArtikla = "Dell Inspiron Gaming PC",
                            TipArtiklaidTipa = 3,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/617LZ7j3uCL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/617LZ7j3uCL._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 25,
                            CijenaArtikla = 5500.0,
                            DetaljniOpis = "Procesor: Intel Core i9-9900K, Grafika: NVIDIA GeForce RTX 2080 Ti, Memorija: CORSAIR 32GB DDR4, ugrađene RGB cijevi te ugrađeno vodeno hlađenje koje će vaše uživanje u igricama učiniti što bolje",
                            KratkiOpis = "Uživajte u igranju igrica na maksimalnoj grafici uz ovu gaming mašinu!",
                            NazivArtikla = "Corsair ONE i160",
                            TipArtiklaidTipa = 3,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/61ZNhGKL2WL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/61ZNhGKL2WL._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 26,
                            CijenaArtikla = 3850.0,
                            DetaljniOpis = "Procesor: 2.7 GHz Intel Core i7, Grafika: NVIDIA GeForce GTX 980M, Memorija: 32 GB GDDR5, posjeduje 28 inčni ekran koji posjeduje PixelSense tehnologiju",
                            KratkiOpis = "Microsoft Surface Studio je potpuno nova klasa uređaja, dizajnirana za kreativne procese!",
                            NazivArtikla = "Microsoft Surface Studio",
                            TipArtiklaidTipa = 3,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/617dm7BrlzL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/617dm7BrlzL._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 27,
                            CijenaArtikla = 70.0,
                            DetaljniOpis = "Integrisani dodatak za dlanove sa prilagodljivom visinom, talasasti dizajn za smanjeni stres i bolje, odnosno prirodnije tipkanje",
                            KratkiOpis = "Ergonomični dizajn sa izdržljivom baterijom!",
                            NazivArtikla = "Logitech MK550 Wireless Wave Keyboard",
                            TipArtiklaidTipa = 4,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/71TwPx+CT9L._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/71TwPx+CT9L._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 28,
                            CijenaArtikla = 30.0,
                            DetaljniOpis = "Radi sa svim čestim aplikacijama preko svih platformi i operativnih sistema uključujući Windows, Mac OS ili Chrome OS",
                            KratkiOpis = "Slušalice sa naprednim digitalnim audio kontrolama!",
                            NazivArtikla = "Logitech USB Headset",
                            TipArtiklaidTipa = 4,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/61CqYq+xwNL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/61CqYq+xwNL._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 29,
                            CijenaArtikla = 40.0,
                            DetaljniOpis = "Podržano na svima platformama uključujući PlayStation 4, Xbox One, Nintendo 3DS, PSP, PC i mnogi drugi, integrisan sa mikrofonom koji transmituje bolju kvalitetu komunikacije sa svojim premium noise-canceling svojstvima",
                            KratkiOpis = "Doživite zvuk na potpuno drugačiji način!",
                            NazivArtikla = "BENGOO G9000 Stereo Headset",
                            TipArtiklaidTipa = 4,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/61NJQcIRM4L._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/61NJQcIRM4L._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 30,
                            CijenaArtikla = 20.0,
                            DetaljniOpis = "Čvrsta izdržljivost koja je testirana na stiskanje preko 5,000.0,000 puta sa garantiranom izdržljivosti, 2.4GHz bežična tehnologija omogućava da istraje na velikim daljinama",
                            KratkiOpis = "Moderni i elegantni izgled sa velikom prezisnošću!",
                            NazivArtikla = "VicTsing MM057 2.4G Wireless Mouse",
                            TipArtiklaidTipa = 4,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/718i4jG9n2L._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/718i4jG9n2L._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 31,
                            CijenaArtikla = 35.0,
                            DetaljniOpis = "Optimalna brzina i performanse za microSDHC kompatibilne uređaje, rating: class 10 (bazirano na SD 2.00 specifikaciji)",
                            KratkiOpis = "Memorija pogodna za skladištenje digitalnog sadržaja kao što su fotografije visoke kvalitete, videi, muzika i više!",
                            NazivArtikla = "SanDisk 32GB X2 (64GB)",
                            TipArtiklaidTipa = 4,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/811Wa0biKIL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/811Wa0biKIL._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 32,
                            CijenaArtikla = 45.0,
                            DetaljniOpis = "Udobne tipke kao i integrisani touchpad pružit će vam najbolje iskustvo, posjeduje distancu čak od 10 metara baziran na Plug-and-play dizajnu, sadrži bateriju koja traje 18 mjeseci te radi na Windows 7, 8, 10 kao i Android 5.0 i dalje te Chrome OS",
                            KratkiOpis = "Uživajte u kontroli vašeg računara konektovanog na TV bez ikakvog napora!",
                            NazivArtikla = "Logitech K400 Plus Wireless Touch TV Keyboard",
                            TipArtiklaidTipa = 4,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/716p8b4Y+eL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/716p8b4Y+eL._AC_UL654_FMwebp_QL65_.jpg"
                        },
                        new
                        {
                            IdArtikla = 33,
                            CijenaArtikla = 100.0,
                            DetaljniOpis = "Posjeduje optički senzor od čak 16000 DPI koji pruža određivanje osjetljivosti kroz reprogramibilne tipke za igranje, do čak 19 programibilnih tipki koji omogućavaju remapiranje i dodjelu kompleksnih makro funkcija, pored toga posjeduje i Chroma RGB Color profile koji uključuje 16.8 miliona kombinacija boja",
                            KratkiOpis = "Doživi potpunu kontrolu u svojim rukama bez obzira koju igru igrate!",
                            NazivArtikla = "Razer Naga Trinity Gaming Mouse",
                            TipArtiklaidTipa = 4,
                            URLMaleSlike1 = "https://m.media-amazon.com/images/I/81xeyiadbaL._AC_UL654_FMwebp_QL65_.jpg",
                            URLSlike1 = "https://m.media-amazon.com/images/I/81xeyiadbaL._AC_UL654_FMwebp_QL65_.jpg"
                        });
                });

            modelBuilder.Entity("BestDeal.Models.Korpa", b =>
                {
                    b.Property<string>("IdKorpe")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("IdKorpe");

                    b.ToTable("Korpa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korpa");
                });

            modelBuilder.Entity("BestDeal.Models.Narudzba", b =>
                {
                    b.Property<int>("IdNarudzbe")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumVrijemeNarudzbe");

                    b.Property<string>("OdabraniArtikliIdKorpe");

                    b.HasKey("IdNarudzbe");

                    b.HasIndex("OdabraniArtikliIdKorpe");

                    b.ToTable("Narudzba");
                });

            modelBuilder.Entity("BestDeal.Models.Obavijest", b =>
                {
                    b.Property<int>("IdObavijesti")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("TekstObavijesti")
                        .IsRequired();

                    b.HasKey("IdObavijesti");

                    b.ToTable("Obavijest");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Obavijest");
                });

            modelBuilder.Entity("BestDeal.Models.Recenzija", b =>
                {
                    b.Property<int>("IdRecenzije")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BatteryLifeRating");

                    b.Property<double>("DesignRating");

                    b.Property<double>("OverallRating");

                    b.Property<double>("PerformanceRating");

                    b.HasKey("IdRecenzije");

                    b.ToTable("Recenzija");
                });

            modelBuilder.Entity("BestDeal.Models.Tip", b =>
                {
                    b.Property<int>("idTipa");

                    b.Property<string>("Ime");

                    b.HasKey("idTipa");

                    b.ToTable("Tip");

                    b.HasData(
                        new
                        {
                            idTipa = 1,
                            Ime = "Laptopi"
                        },
                        new
                        {
                            idTipa = 2,
                            Ime = "Mobiteli"
                        },
                        new
                        {
                            idTipa = 3,
                            Ime = "Računari"
                        },
                        new
                        {
                            idTipa = 4,
                            Ime = "Računarska oprema"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("IdentityUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BestDeal.Models.KorpaInfo", b =>
                {
                    b.HasBaseType("BestDeal.Models.Korpa");

                    b.Property<int?>("AIdArtikla");

                    b.Property<string>("IdKorpe1");

                    b.Property<int>("KolicinaArtikla");

                    b.Property<string>("KorpaIdKorpe");

                    b.HasIndex("AIdArtikla");

                    b.HasIndex("KorpaIdKorpe");

                    b.ToTable("KorpaInfo");

                    b.HasDiscriminator().HasValue("KorpaInfo");
                });

            modelBuilder.Entity("BestDeal.Models.ChatObavijest", b =>
                {
                    b.HasBaseType("BestDeal.Models.Obavijest");

                    b.ToTable("ChatObavijest");

                    b.HasDiscriminator().HasValue("ChatObavijest");
                });

            modelBuilder.Entity("BestDeal.Models.NarudzbeObavijest", b =>
                {
                    b.HasBaseType("BestDeal.Models.Obavijest");

                    b.ToTable("NarudzbeObavijest");

                    b.HasDiscriminator().HasValue("NarudzbeObavijest");
                });

            modelBuilder.Entity("BestDeal.Models.Artikal", b =>
                {
                    b.HasOne("BestDeal.Models.Tip", "TipArtikla")
                        .WithMany()
                        .HasForeignKey("TipArtiklaidTipa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BestDeal.Models.Narudzba", b =>
                {
                    b.HasOne("BestDeal.Models.Korpa", "OdabraniArtikli")
                        .WithMany()
                        .HasForeignKey("OdabraniArtikliIdKorpe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BestDeal.Models.KorpaInfo", b =>
                {
                    b.HasOne("BestDeal.Models.Artikal", "A")
                        .WithMany()
                        .HasForeignKey("AIdArtikla");

                    b.HasOne("BestDeal.Models.Korpa")
                        .WithMany("ArtikliKolicina")
                        .HasForeignKey("KorpaIdKorpe");
                });
#pragma warning restore 612, 618
        }
    }
}
